export const Gdansk = [
    { value: '1', label: 'Aniołki' },
    { value: '2', label: 'Brętowo' },
    { value: '3', label: 'Brzeźno' },
    { value: '4', label: 'Chełm' },
    { value: '5', label: 'Jasień' },
    { value: '6', label: 'Kokoszki' },
    { value: '7', label: 'Krakowiec- Górki Zachodnie' },
    { value: '8', label: 'Letnica' },
    { value: '9', label: 'Matarnia' },
    { value: '10', label: 'Młyniska' },
    { value: '11', label: 'Nowy Port' },
    { value: '12', label: 'Oliwa' },
    { value: '13', label: 'Olszynka' },
    { value: '14', label: 'Orunia Górna-Gdańsk Południe' },
    { value: '15', label: 'Orunia-Św. Wojciech-Lipce' },
    { value: '16', label: 'Osowa' },
    { value: '17', label: 'Piecki-Migowo' },
    { value: '18', label: 'Przeróbka' },
    { value: '19', label: 'Przymorze Małe' },
    { value: '20', label: 'Przymorze Wielkie' },
    { value: '21', label: 'Rudniki' },
    { value: '22', label: 'Siedlce' },
    { value: '23', label: 'Stogi' },
    { value: '24', label: 'Strzyża' },
    { value: '25', label: 'Suchanino' },
    { value: '26', label: 'Śródmieście' },
    { value: '27', label: 'Ujeścisko-Łostowice' },
    { value: '28', label: 'VII Dwór' },
    { value: '29', label: 'Wrzeszcz Dolny' },
    { value: '30', label: 'Wrzeszcz Górny' },
    { value: '31', label: 'Wyspa Sobieszewska' },
    { value: '32', label: 'Wzgórze Mickiewicza' },
    { value: '33', label: 'Zaspa Młyniec' },
    { value: '34', label: 'Zaspa Rozstaje' },
    { value: '35', label: 'Żabianka-Wejhera-Jelit.Tysiąc.' },
];

export const Sopot = [
    { value: '1', label: 'Brodwino' },
    { value: '2', label: 'Dolny Sopot' },
    { value: '3', label: 'Górny Sopot' },
    { value: '4', label: 'Kamienny Potok' },
    { value: '5', label: 'Karlikowo' },
    { value: '6', label: 'Stawowie' },
    { value: '7', label: 'Świemirowo' },
];
export const Gdynia = [
    { value: '1', label: 'Babie Doły' },
    { value: '2', label: 'Chwarzno-Wiczlino' },
    { value: '3', label: 'Chylonia' },
    { value: '4', label: 'Cisowa' },
    { value: '5', label: 'Działki Leśne' },
    { value: '6', label: 'Dąbrowa' },
    { value: '7', label: 'Grabówek' },
    { value: '8', label: 'Kamienna Góra' },
    { value: '9', label: 'Karwiny' },
    { value: '10', label: 'Leszczynki' },
    { value: '11', label: 'Mały Kack' },
    { value: '12', label: 'Obłuże' },
    { value: '13', label: 'Oksywie' },
    { value: '14', label: 'Orłowo' },
    { value: '15', label: 'Pogórze' },
    { value: '16', label: 'Pustki Cisowskie-Demptowo' },
    { value: '17', label: 'Redłowo' },
    { value: '18', label: 'Śródmieście' },
    { value: '19', label: 'Wielki Kack' },
    { value: '20', label: 'Witomino' },
    { value: '21', label: 'Wzgórze Św. Maksymiliana' },
];